-- Tests for block type detection from content
-- Phase 5.8: Block Type Conversion

describe('detection', function()
  local detection

  before_each(function()
    package.loaded['neotion.model.blocks.detection'] = nil
    detection = require('neotion.model.blocks.detection')
  end)

  describe('detect_type', function()
    describe('bulleted_list_item detection', function()
      it('should detect "- " prefix as bulleted_list_item', function()
        local block_type, prefix = detection.detect_type('- item text')
        assert.are.equal('bulleted_list_item', block_type)
        assert.are.equal('- ', prefix)
      end)

      it('should detect "* " prefix as bulleted_list_item', function()
        local block_type, prefix = detection.detect_type('* item text')
        assert.are.equal('bulleted_list_item', block_type)
        assert.are.equal('* ', prefix)
      end)

      it('should detect "+ " prefix as bulleted_list_item', function()
        local block_type, prefix = detection.detect_type('+ item text')
        assert.are.equal('bulleted_list_item', block_type)
        assert.are.equal('+ ', prefix)
      end)

      it('should require space after dash', function()
        local block_type, prefix = detection.detect_type('-no space')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should require space after asterisk', function()
        local block_type, prefix = detection.detect_type('*no space')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should require space after plus', function()
        local block_type, prefix = detection.detect_type('+no space')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should detect empty bullet item', function()
        local block_type, prefix = detection.detect_type('- ')
        assert.are.equal('bulleted_list_item', block_type)
        assert.are.equal('- ', prefix)
      end)

      it('should handle bullet with only whitespace content', function()
        local block_type, prefix = detection.detect_type('-   ')
        assert.are.equal('bulleted_list_item', block_type)
        assert.are.equal('- ', prefix)
      end)
    end)

    describe('quote detection', function()
      it('should detect "| " prefix as quote', function()
        local block_type, prefix = detection.detect_type('| quoted text')
        assert.are.equal('quote', block_type)
        assert.are.equal('| ', prefix)
      end)

      it('should require space after pipe', function()
        local block_type, prefix = detection.detect_type('|no space')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should detect empty quote', function()
        local block_type, prefix = detection.detect_type('| ')
        assert.are.equal('quote', block_type)
        assert.are.equal('| ', prefix)
      end)

      it('should NOT detect > as quote (reserved for toggle)', function()
        local block_type, prefix = detection.detect_type('> text')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)
    end)

    describe('paragraph (no prefix)', function()
      it('should return nil for plain text', function()
        local block_type, prefix = detection.detect_type('just plain text')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should return nil for empty string', function()
        local block_type, prefix = detection.detect_type('')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should return nil for whitespace only', function()
        local block_type, prefix = detection.detect_type('   ')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should return nil for dash in middle of text', function()
        local block_type, prefix = detection.detect_type('some - text')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should return nil for pipe in middle of text', function()
        local block_type, prefix = detection.detect_type('some | text')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)
    end)

    describe('edge cases', function()
      it('should handle nil input gracefully', function()
        local block_type, prefix = detection.detect_type(nil)
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should not detect indented prefixes (Phase 5.10 scope)', function()
        -- Indented bullets are for nested lists, not supported yet
        local block_type, prefix = detection.detect_type('  - indented')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)

      it('should not detect tab-indented prefixes', function()
        local block_type, prefix = detection.detect_type('\t- indented')
        assert.is_nil(block_type)
        assert.is_nil(prefix)
      end)
    end)
  end)

  describe('strip_prefix', function()
    it('should strip bullet prefix and return content', function()
      local content = detection.strip_prefix('- item text', '- ')
      assert.are.equal('item text', content)
    end)

    it('should strip quote prefix and return content', function()
      local content = detection.strip_prefix('| quoted', '| ')
      assert.are.equal('quoted', content)
    end)

    it('should return original if prefix does not match', function()
      local content = detection.strip_prefix('no prefix here', '- ')
      assert.are.equal('no prefix here', content)
    end)

    it('should handle empty content after prefix', function()
      local content = detection.strip_prefix('- ', '- ')
      assert.are.equal('', content)
    end)

    it('should handle nil line', function()
      local content = detection.strip_prefix(nil, '- ')
      assert.are.equal('', content)
    end)

    it('should handle nil prefix', function()
      local content = detection.strip_prefix('some text', nil)
      assert.are.equal('some text', content)
    end)
  end)

  describe('get_prefix_for_type', function()
    it('should return "- " for bulleted_list_item', function()
      local prefix = detection.get_prefix_for_type('bulleted_list_item')
      assert.are.equal('- ', prefix)
    end)

    it('should return "| " for quote', function()
      local prefix = detection.get_prefix_for_type('quote')
      assert.are.equal('| ', prefix)
    end)

    it('should return nil for paragraph', function()
      local prefix = detection.get_prefix_for_type('paragraph')
      assert.is_nil(prefix)
    end)

    it('should return nil for unknown types', function()
      local prefix = detection.get_prefix_for_type('unknown_type')
      assert.is_nil(prefix)
    end)

    it('should return nil for nil input', function()
      local prefix = detection.get_prefix_for_type(nil)
      assert.is_nil(prefix)
    end)
  end)

  describe('should_convert', function()
    -- Helper to check if a block with current_type containing content should convert
    it('should return true when paragraph has bullet prefix', function()
      local should, target = detection.should_convert('paragraph', '- item')
      assert.is_true(should)
      assert.are.equal('bulleted_list_item', target)
    end)

    it('should return true when paragraph has quote prefix', function()
      local should, target = detection.should_convert('paragraph', '| quoted')
      assert.is_true(should)
      assert.are.equal('quote', target)
    end)

    it('should return false when paragraph has no prefix', function()
      local should, target = detection.should_convert('paragraph', 'plain text')
      assert.is_false(should)
      assert.is_nil(target)
    end)

    it('should return true when bullet loses its prefix (becomes paragraph)', function()
      local should, target = detection.should_convert('bulleted_list_item', 'no prefix anymore')
      assert.is_true(should)
      assert.are.equal('paragraph', target)
    end)

    it('should return false when bullet keeps its prefix', function()
      local should, target = detection.should_convert('bulleted_list_item', '- still a bullet')
      assert.is_false(should)
      assert.is_nil(target)
    end)

    it('should return true when quote loses its prefix', function()
      local should, target = detection.should_convert('quote', 'no longer quoted')
      assert.is_true(should)
      assert.are.equal('paragraph', target)
    end)

    it('should return false when quote keeps its prefix', function()
      local should, target = detection.should_convert('quote', '| still quoted')
      assert.is_false(should)
      assert.is_nil(target)
    end)

    it('should return true when bullet changes to quote', function()
      local should, target = detection.should_convert('bulleted_list_item', '| now a quote')
      assert.is_true(should)
      assert.are.equal('quote', target)
    end)

    it('should return true when quote changes to bullet', function()
      local should, target = detection.should_convert('quote', '- now a bullet')
      assert.is_true(should)
      assert.are.equal('bulleted_list_item', target)
    end)

    it('should handle empty content', function()
      local should, target = detection.should_convert('paragraph', '')
      assert.is_false(should)
      assert.is_nil(target)
    end)

    it('should handle nil content', function()
      local should, target = detection.should_convert('paragraph', nil)
      assert.is_false(should)
      assert.is_nil(target)
    end)
  end)
end)
